<?php
echo '<html>';

	echo '<head>';
		echo '<script type="text/javascript">';
		echo '
		
			function trim1(str)
			{
			    if(!str || typeof str != \'string\')
				{
			        return null;
				} 
			    return str.replace(/^[\\s]+/,\'\').replace(/[\\s]+$/,\'\');
			}
			
			function trim(str)
			{
				if(!str || typeof str != \'string\')
				{
			        return null;
				} 
			    return str.replace(/^[\\s]+/,\'\').replace(/[\\s]+$/,\'\').replace(/[\s]{2,}/,\' \');
			}
		
		
		
		function validateForm()
		{
			var name = document.getElementById(\'name\').value;
			var email = document.getElementById(\'email\').value;
			var pword = document.getElementById(\'password\').value;
			var confpword = document.getElementById(\'confpassword\').value;			
			
			var emailPattern=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$/;	
			
			
			if(name === \'\' || name === "" || trim1(name) === \'\' || trim1(name) === "")
			{
				alert("Name is required");
				 document.getElementById(\'email\').value = trim1(name);
				return false;
			}
			else if(email === \'\' || email === "")
			{
				alert("Email Id is required");
				return false;
			}
			else if(trim(pword) === \'\' || trim(pword) === "" || pword ===\'\' || pword ==="")
			{
				alert("Password is required");
				return false;
			}
			else if(trim(confpword) === "" || trim(confpword) === \'\' || confpword ===\'\' || confpword === "")
			{
				alert("Confirm password should be same as password");
				return false;
			}
			else if(!emailPattern.test(email))
			{
				alert("Email address not valid");
				return false;
			}
			else if(pword.length >8)
			{
				alert("Password length should not be more than 8");
			}
			else
			{
				alert("Everything is fine");
			}
			
		}';
		
		echo '</script>';
	echo '</head>';

	echo '<body>';
		echo '<center><h1>HTML form generated by PHP</h1></center>';
		
		echo '<form method="post" >';
			echo 'Name :';echo '<input type="text" size="40" id="name">';
			echo 'Email :';echo '<input type="text" size="40" id="email">';
			echo 'Password :';echo '<input type="password" size="40" id="password">';
			echo 'Confirm Password :';echo '<input type="password" size="40" id="confpassword">';
			echo '<input type="submit" value="Submit" onclick="javascript:validateForm();">';
		echo '</form>';
	echo '</body>';

echo '</html>';
?>